title: Trial page
author: zsofi777
email: kovagozsofia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my site which I created during the GitHub Learning Lab course.

# social links
github_username:  zsofi777

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
